import React,{useState}from'react';
import{LayoutDashboard,CalendarDays,Scissors,GraduationCap,ShoppingCart,Package,Users,UserRound,Receipt,ChartNoAxesCombined,MessageCircle,Settings,PanelLeftClose,PanelLeftOpen,PawPrint,TrendingUp,Clock,Plus,AlertTriangle}from'lucide-react';
const nav=[['Dashboard',LayoutDashboard],['Appointments',CalendarDays],['Grooming',Scissors],['Training',GraduationCap],['Retail / POS',ShoppingCart],['Inventory',Package],['Clients',Users],['Employees',UserRound],['Expenses',Receipt],['Reports',ChartNoAxesCombined],['WhatsApp Hub',MessageCircle],['Settings',Settings]];
const kpis=[['Today’s Appointments','12',CalendarDays],['Grooming in Progress','4',Scissors],['Training Sessions','6',GraduationCap],['Sales Today','QAR 3,480',ShoppingCart]];
const events=[['09:00','Luna','Full Groom','Sara','In Progress','🐩'],['10:30','Max','Wash','Ali','Upcoming','🐕'],['12:00','Coco','Training','Rami','Upcoming','🐶'],['15:00','Milo','Nail Trim','Sara','Completed','🐕‍🦺']];
const alerts=[['Low inventory','7 products need reordering'],['Pending payments','3 invoices outstanding'],['WhatsApp unread','8 customer messages'],['Attendance issue','1 employee arrived late']];
export default function App(){const[active,setActive]=useState('Dashboard');const[collapsed,setCollapsed]=useState(false);const[modal,setModal]=useState('');return <div className="app">
<aside className={collapsed?'side collapsed':'side'}><div className="brand"><span><PawPrint/></span>{!collapsed&&<b>Mission Pawssible<small>Pet Business CRM</small></b>}</div><nav>{nav.map(([n,I])=><button title={n} className={active===n?'active':''} onClick={()=>setActive(n)} key={n}><I/>{!collapsed&&<span>{n}</span>}</button>)}</nav><button className="collapse" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}{!collapsed&&'Collapse'}</button></aside>
<main><header><div><small>Mission control</small><h1>{active}</h1></div><button className="primary" onClick={()=>setModal('New Appointment')}><Plus/> New Appointment</button></header>
{active==='Dashboard'?<><section className="kpis">{kpis.map(([n,v,I])=><article key={n}><div><small>{n}</small><strong>{v}</strong><em><TrendingUp/> 8% this week</em></div><I className="paw"/></article>)}</section><section className="grid"><article className="panel"><div className="panelTitle"><h2>Appointment Timeline</h2><Clock/></div>{events.map(e=><div className="event" key={e[0]}><span className="pet">{e[5]}</span><b>{e[0]}</b><div><strong>{e[1]} · {e[2]}</strong><small>Assigned to {e[3]}</small></div><i className={e[4].replace(' ','').toLowerCase()}>{e[4]}</i></div>)}</article><article className="panel"><div className="panelTitle"><h2>Alerts</h2><AlertTriangle/></div>{alerts.map(a=><div className="alert" key={a[0]}><span>!</span><div><strong>{a[0]}</strong><small>{a[1]}</small></div></div>)}</article></section><section className="panel quick"><h2>Quick Actions</h2>{['New Appointment','New Sale','Add Expense','Add Client'].map(x=><button onClick={()=>setModal(x)} key={x}><Plus/>{x}</button>)}</section></>:<section className="panel empty"><PawPrint/><h2>{active}</h2><p>This module is scaffolded and ready to connect to your API and PostgreSQL database.</p><button className="primary" onClick={()=>setModal('Add '+active)}>Add record</button></section>}
</main>{modal&&<div className="overlay"><form className="modal" onSubmit={e=>{e.preventDefault();setModal('')}}><h2>{modal}</h2><input placeholder="Client name" required/><input placeholder="Pet / item"/><input type="datetime-local"/><textarea placeholder="Notes"/><div><button type="button" onClick={()=>setModal('')}>Cancel</button><button className="primary">Save</button></div></form></div>}</div>}
